### ISSUE TITLE
Failed to run `Command line interface` tutorial.

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/LobsterPy#319]
I try to run the [Command line interface](https://jageo.github.io/LobsterPy/tutorial/commandlineinterface.html#) tutorial step-by-step according to the document. But failed at the following steps:

```shell
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy description --json description.json
usage: lobsterpy [-h]
                 {create-inputs,createinputs,description,description-quality,plot-automatic,plot-auto,automatic-plot,automaticplot,auto-plot,autoplot,plot-automatic-ia,plot-auto-ia,automatic-plot-ia,automaticplotia,autoplotia,auto-plot-ia,plot-dos,plotdos,plot-icohp-distance,ploticohpdistance,plot}
                 ...
lobsterpy: error: unrecognized arguments: --json description.json

(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy calc-description --potcar-symbols "Na_pv Cl" --bvacomp --doscomp --calcqualityjson calc_quality_description.json
usage: lobsterpy [-h]
                 {create-inputs,createinputs,description,description-quality,plot-automatic,plot-auto,automatic-plot,automaticplot,auto-plot,autoplot,plot-automatic-ia,plot-auto-ia,automatic-plot-ia,automaticplotia,autoplotia,auto-plot-ia,plot-dos,plotdos,plot-icohp-distance,ploticohpdistance,plot}
                 ...
lobsterpy: error: argument action: invalid choice: 'calc-description' (choose from 'create-inputs', 'createinputs', 'description', 'description-quality', 'plot-automatic', 'plot-auto', 'automatic-plot', 'automaticplot', 'auto-plot', 'autoplot', 'plot-automatic-ia', 'plot-auto-ia', 'automatic-plot-ia', 'automaticplotia', 'autoplotia', 'auto-plot-ia', 'plot-dos', 'plotdos', 'plot-icohp-distance', 'ploticohpdistance', 'plot')
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy automatic-plot --title 'Automatic COHP plot' --save-plot COHP.png
/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/outputs.py:391: UserWarning: Please consider using the new Lobster version. See www.cohp.de.
  warnings.warn("Please consider using the new Lobster version. See www.cohp.de.")
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/lobsterpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 33, in main
    run(args)
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 782, in run
    analyse = Analysis(
              ^^^^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 163, in __init__
    self.setup_env()
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 229, in setup_env
    raise err
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 205, in setup_env
    self.chemenv = LobsterNeighbors(
                   ^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/lobsterenv.py", line 121, in __init__
    self.ICOHP = Icohplist(are_coops=are_coops, are_cobis=are_cobis, filename=filename_icohp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/outputs.py", line 442, in __init__
    length = float(line[3])
             ^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'for'
```
Do you have any tips and hints for fixing these problems?

Regards,
Zhao

**Comment by naik-aakash** [comment]
Hi @hongyi-zhao , I have fixed the tutorial snippet now in the docs. Somehow I overlooked to update the commands in the CLI tutorials. The correct command to get description is `lobsterpy description --file-json description.json`

**Comment by hongyi-zhao** [comment]
Still failed, as shown below:

```
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy description --file-json description.json
/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/outputs.py:391: UserWarning: Please consider using the new Lobster version. See www.cohp.de.
  warnings.warn("Please consider using the new Lobster version. See www.cohp.de.")
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/lobsterpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 33, in main
    run(args)
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 782, in run
    analyse = Analysis(
              ^^^^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 163, in __init__
    self.setup_env()
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 229, in setup_env
    raise err
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py", line 205, in setup_env
    self.chemenv = LobsterNeighbors(
                   ^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/lobsterenv.py", line 121, in __init__
    self.ICOHP = Icohplist(are_coops=are_coops, are_cobis=are_cobis, filename=filename_icohp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/lobster/outputs.py", line 442, in __init__
    length = float(line[3])
             ^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'for'
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy description-quality --potcar-symbols "Na_pv Cl" --bvacomp --doscomp --file-calc-quality-json calc_quality_description.json
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/lobsterpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 33, in main
    run(args)
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 1077, in run
    dos_files = get_file_paths(
                ^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/featurize/utils.py", line 70, in get_file_paths
    raise Exception(f"Files {missing_files} not found in {lobster_path.name}.")
Exception: Files ['DOSCAR.LSO.lobster'] not found in Basis_0.
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ pip list|grep lobs
lobsterpy                     0.4.6                   /home/werner/Public/repo/github.com/JaGeo/LobsterPy.git
```

**Comment by naik-aakash** [comment]
Ops I see, just pushing a fix in few minutes.

**Comment by naik-aakash** [comment]
Hi @hongyi-zhao , the issue with exception should also be fixed via  PR #321

**Comment by naik-aakash** [comment]
Hi @hongyi-zhao , I suspect you are now using LOBSTER 5.1 ? In this case, pymatgen needs to be updated to deal with ICOHP/ ICOBI / ICOOP files as I see in the changelog of 5.1.0, these file outputs have been updated. 

![image](https://github.com/user-attachments/assets/e317a51d-5632-41e4-8fc9-0c116771a7b0)

I would suggest try using LOBSTER 5.0 or lower. As adding support to 5.1 might take time if output file format is changed, parsers need to be updated and I do not know, how much of a change it is at this point. Will try to have a look at them soon. 

Also, currently not all features of LOBSTER 5.0 is supported via pymatgen/lobsterpy. See #170, this is on our todo. We will then add 5.1.0 support when working on it.

**Comment by JaGeo** [comment]
@hongyi-zhao If you need it now, you are surely also invited to fix the input/output methods in pymatgen. We will try to get it done after the summer, likely.

**Comment by hongyi-zhao** [comment]
> Hi @hongyi-zhao , I suspect you are now using LOBSTER 5.1 ?

Yes.
```shell
werner@x13dai-t:~$ lobster
LOBSTER v5.1.0 (g++ 9.3.0)
Copyright (C) 2024 by Chair of Solid-State and Quantum Chemistry, RWTH Aachen.
All rights reserved. Contributions by S. Maintz, V. L. Deringer, M. Esser, R. Nelson, C. Ertural, P. C. Mueller, M. Pauls, L. Sann, D. Schnieders, A. L. Tchougreeff, and R. Dronskowski
starting on host x13dai-t on 2024-07-31 at 15:12:19 CST using 96 threads
detecting used PAW program...
ERROR: could not determine which program was used for the quantum-chemical calculation.
ERROR: Make sure all required files are in the working directory and are not empty.

```

**Comment by hongyi-zhao** [comment]
So far, I've successfully run most of the commands shown in [the tutorial](https://jageo.github.io/LobsterPy/tutorial/commandlineinterface.html). However, there are still some issues as follows:

1. I followed the steps in the tutorial exactly, but I noticed that the results of the following two commands are not the same as shown in the tutorial:
 
```
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy description --file-json description.json
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['international']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cohp/analyze.py:870: UserWarning: The bonding, antibonding integral/percent values are numerical estimate. These values are sensitive to COHPstartEnergy parameter. If COHPstartEnergy value does not cover entire range of VASP calculations then absolute value of ICOHP_sum might not be equivalent to (bonding- antibonding) integral values.
  ) = self._integrate_antbdstates_below_efermi(cohp, start=self.start)
The compound CdF2 has 1 symmetry-independent cation(s) with relevant cation-anion interactions: Cd1.
Cd1 has a cubic (CN=8) coordination environment. It has 8 Cd-F (mean ICOHP: -0.62 eV, 27.743 percent antibonding interaction below EFermi) bonds.

(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ jq < description.json 
{
  "formula": "CdF2",
  "max_considered_bond_length": 5.98538,
  "limit_icohp": [
    -1.7976931348623157e+308,
    -0.062174
  ],
  "number_of_considered_ions": 1,
  "sites": {
    "0": {
      "env": "C:8",
      "bonds": {
        "F": {
          "ICOHP_mean": "-0.62",
          "ICOHP_sum": "-4.97",
          "has_antibdg_states_below_Efermi": true,
          "number_of_bonds": 8,
          "bonding": {
            "integral": 8.1,
            "perc": 0.72257
          },
          "antibonding": {
            "integral": 3.11,
            "perc": 0.27743
          }
        }
      },
      "ion": "Cd",
      "charge": 1.57,
      "relevant_bonds": [
        "29",
        "30",
        "33",
        "40",
        "53",
        "60",
        "63",
        "64"
      ]
    }
  },
  "type_charges": "Mulliken"
}

(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy description-quality --potcar-symbols "Na_pv Cl" --bvacomp --doscomp --file-calc-quality-json calc_quality_description.json
/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/src/pymatgen/io/vasp/outputs.py:160: UserWarning: Float overflow (*******) encountered in vasprun
  warnings.warn("Float overflow (*******) encountered in vasprun")
/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py:1085: UserWarning: Consider using DOSCAR.LSO.lobster, as non LSO DOS from LOBSTER can have negative DOS values
  quality_dict = Analysis.get_lobster_calc_quality_summary(
/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py:1085: UserWarning: Input DOS files have very few points in the energy interval and thus comparisons will not be reliable. Please rerun the calculations with higher number of DOS points. Set NEDOS and COHPSteps tags to >= 2000 in VASP and LOBSTER calculations, respectively.
  quality_dict = Analysis.get_lobster_calc_quality_summary(
The LOBSTER calculation used minimal basis. The absolute and total charge spilling for the calculation is 0.65 and 0.0 %, respectively. The projected wave function is completely orthonormalized as no bandOverlaps.lobster file is generated during the LOBSTER run. The atomic charge signs from Mulliken population analysis agree with the bond valence analysis. The atomic charge signs from Loewdin population analysis agree with the bond valence analysis. The Tanimoto index from DOS comparisons in the energy range between -5, 0 eV for s, d, p, summed orbitals are: 0.7137, 0.6449, 0.3208, 0.4766.

```
2. The following command still fails

```
(datasci) werner@x13dai-t:~/Public/repo/github.com/JaGeo/Create_inputs_example/Basis_0$ lobsterpy plot-dos --summedspins
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/lobsterpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 33, in main
    run(args)
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/cli.py", line 1114, in run
    req_files = get_file_paths(path_to_lobster_calc=Path(os.getcwd()), requested_files=["structure", "doscar"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/src/lobsterpy/featurize/utils.py", line 70, in get_file_paths
    raise Exception(f"Files {missing_files} not found in {lobster_path.name}.")
Exception: Files ['DOSCAR.LSO.lobster'] not found in Basis_0.
```

The lobster version to do the above test is shown below:

```shell
$ module list 

Currently Loaded Modules:
  1) lmod   2) lobster/5.0.0
```

**Comment by JaGeo** [comment]
@hongyi-zhao thank you for reporting this to us. I hope we can check it out soon.
